### PR TITLE
Garbage Monitoring System

### PR DESCRIPTION
**Pull request by kunalbandooni**
Be open to make any new changes. :)

### CODE REVIEW

**Comment by kunalbandooni** [comment]
Open to any changes :)

**Review by kunalbandooni — COMMENTED** [review]
Great changes were made in my previous project, "Garbage Monitoring System".  Also added "Automated Parking".

**Comment by NitinShaily** [comment]
@kunalbandooni  you missed the readme file

**Comment by kunalbandooni** [comment]
@NitinShaily Oops!! Missed that by chance, now added.

**Pull request merged**
