### PR TITLE
Create Indexer

### PR DESCRIPTION
**Pull request by ritvik-garg**
Wikipedia Search Engine : built on the full English corpus of wikipedia (~80 GB)

I am not able to add complete folder due to access issue, therefore couldn't add README file

### CODE REVIEW

**Comment by NitinShaily** [comment]
@ritvik-garg  really like your work but please look at the contribution file before making a pull request.. you have to add your project folder in a dedicated directory  and have to add a readme  describing what you have actually done

**Comment by ritvik-garg** [comment]
I was facing access issue while pushing my code onto your repo.
image

Let me know how to resolve this .

**Comment by NitinShaily** [comment]
@ritvik-garg yes you can't directly push changes to this repo instead make changes in your forked repo and make a pull request
'

**Comment by ritvik-garg** [comment]
Thanks for helping out.

I have added my 2 projects, and have raised PR.

Have a look, and let me know if any changes are required.

**Pull request merged**
